"""Initial migration

Revision ID: 354f45620bbe
Revises: 
Create Date: 2025-01-22 18:58:35.405569

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '354f45620bbe'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('drivers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('phone_number', sa.String(), nullable=True),
    sa.Column('plate_number', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_drivers_phone_number'), 'drivers', ['phone_number'], unique=True)
    op.create_index(op.f('ix_drivers_plate_number'), 'drivers', ['plate_number'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('hashed_password', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('user_type', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('expense',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('driver_id', sa.Integer(), nullable=False),
    sa.Column('driver_name', sa.String(), nullable=True),
    sa.Column('amount', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trips',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('loading_date', sa.Date(), nullable=True),
    sa.Column('atc_order_number', sa.String(), nullable=True),
    sa.Column('driver_id', sa.Integer(), nullable=False),
    sa.Column('driver_name', sa.String(), nullable=True),
    sa.Column('dispatch', sa.Integer(), nullable=True),
    sa.Column('bonus', sa.Integer(), nullable=True),
    sa.Column('diesel_litres', sa.Integer(), nullable=True),
    sa.Column('diesel_amount', sa.Integer(), nullable=True),
    sa.Column('diesel_date', sa.Date(), nullable=True),
    sa.Column('customer_name', sa.String(), nullable=True),
    sa.Column('amount', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trips_atc_order_number'), 'trips', ['atc_order_number'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trips_atc_order_number'), table_name='trips')
    op.drop_table('trips')
    op.drop_table('expense')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_drivers_plate_number'), table_name='drivers')
    op.drop_index(op.f('ix_drivers_phone_number'), table_name='drivers')
    op.drop_table('drivers')
    # ### end Alembic commands ###
